"""add event type and time to storage

Revision ID: 77cbf9951072
Revises: a1b39c75c083
Create Date: 2020-09-20 07:55:40.557134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cbf9951072'
down_revision = 'a1b39c75c083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_events', sa.Column('event_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('storage_events', sa.Column('event_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_events', 'event_type')
    op.drop_column('storage_events', 'event_time')
    # ### end Alembic commands ###
